# Generated by Django 5.0.2 on 2024-04-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings')], default='Checking', max_length=8)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReccurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('receiver', models.CharField(max_length=65)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.CharField(choices=[('minutely', 'Minutely'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=50)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=65)),
                ('ttype', models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit'), ('Payment', 'Payment'), ('Transfer', 'Transfer'), ('Reccurring', 'Reccurring')], default='Deposit', max_length=10)),
                ('receiver', models.CharField(max_length=65)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.bankaccount')),
            ],
        ),
    ]
