FROM mysql:latest

# Environment variables
ENV MYSQL_ROOT_PASSWORD=team1
ENV MYSQL_DATABASE=agile_bank
ENV MYSQL_USER=team1
ENV MYSQL_PASSWORD=team1

# Expose the MySQL port
EXPOSE 3306

# Start MySQL service
CMD ["mysqld"]