# Generated by Django 5.0.2 on 2024-03-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_bankaccount_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='Savings',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='type',
            field=models.CharField(choices=[('Checking', 'Checking'), ('Savings', 'Savings')], default='Checking', max_length=8),
        ),
    ]
